https://codecov.io/gh/mintoko/fidl2adoc[image:https://codecov.io/gh/mintoko/fidl2adoc/branch/main/graph/badge.svg?token=DN46EMNPVD[codecov]]

= fidl2adoc

== Introduction
fidl2adoc is a Python script, which generates documentation from Franca IDL (.fidl) files in AsciiDoc (.adoc), see example link:examples/Test.fidl[Test.fidl] with corresponding link:examples/Test.adoc[Test.adoc].

== Dependencies
Latest version 0.4.1 of https://github.com/zayfod/pyfranca[PyFranca].

Install with:

  pip install pyfranca

== Usage
Generate Test.adoc from Test.fidl with:

  python ./fidl2adoc/fidl2adoc.py -i ./examples/Test.fidl -o ./examples/Test.adoc

Include the generated adoc file in your documentation with

  include::Test.adoc[leveloffset=x]
  
as shown in link:examples/MainDoc.adoc[MainDoc.adoc]. If the generated file should not be used within another document, but as a standalone document instead, use option "-s" or "--standalone":

  python ./fidl2adoc/fidl2adoc.py -i ./examples/Test.fidl -o ./examples/Test_s.adoc -s
  
This will generate a document title and a table of contents in the adoc output file.
