
[[Test3]]
= Interface testpackage.Test3

Version: 2.0

This section is generated from the Franca IDL file for Interface Test3 in package testpackage

Package description: 
Description of the testpackage.


Interface description: 
Description of the Test3 interface

See also: The other interface. 


== Attributes

[[Test3-testAttribute]]
=== Attribute testAttribute


Attribute testAttribute has some description.
    
New paragraph in the attribute description. testAttribute is updated by sending
method testMethod.

[plantuml, test-seq-1]
----
Client -> Server: testMethod(params)
Server -> Client: set testAttribute
----

See also: <<Test3-testMethod>> 


Attribute data type: Array of <<Test3-TestType1>>

== Methods

[[Test3-testMethod]]
=== Method testMethod


Description of testMethod.

See also: <<Test3-testAttribute>> 


Input Parameters:

[options="header",cols="20%,20%,60%"]
|===
|Type|Name|Description
|<<Test3-TestType2>>|testParameter|
Description of the input parameter testParameter.

|===


Output Parameters:

[options="header",cols="20%,20%,60%"]
|===
|Type|Name|Description
|String|testParameter2|
Description of the out parameter testParameter2.

|===


Errors: <<Test3-TestType1>>

== Structs

[[Test3-TestType2]]
=== Struct TestType2


Description of TestType2


Struct fields:

[options="header",cols="20%,20%,60%"]
|===
|Type|Name|Description
|String|structParam1|
Description of structParam1

|Array of UInt32|structParam2|
Description of structParam2

|<<Test3-TestType1>>|structParam3|
Description of structParam3

|===


Used in: 
<<Test3-testMethod>>
[[Test3-TestType3]]
=== Struct TestType3

Extends <<Test3-TestType2>> 


Description of TestType3


Struct fields:

[options="header",cols="20%,20%,60%"]
|===
|Type|Name|Description
|String|structParam1|
Description of structParam1

|Array of UInt32|structParam2|
Description of structParam2

|<<Test3-TestType1>>|structParam3|
Description of structParam3

|<<Test3-MyTypedef>>|structParam4|
Description of structParam4

|===


== Enumerations

[[Test3-TestType1]]
=== Enumeration TestType1


Description of TestType1




[options="header",cols="20%,20%,60%"]
|===
|Enumerator|Value|Description
|INIT|0|
Description of INIT

|STARTING|1|
Description of STARTING

|RUNNING|3|
Description of RUNNING

|SHUTDOWN|4|
Description of SHUTDOWN

|NONE|99|
Description of NONE

|===


Used in: 
<<Test3-testAttribute>>
, 
<<Test3-testMethod>>
, 
<<Test3-TestType2>>

== Typedefs

[[Test3-MyTypedef]]
=== Typedef MyTypedef


Description of MyTypedef




[options="header",cols="20%,20%,60%"]
|===
|Typedef|Type|Description
|MyTypedef|<<Test3-TestType1>>|
Description of MyTypedef

|===


Used in: 
<<Test3-TestType3>>

== Constants

[[Test3-MAX_COUNT]]
=== Constant MAX_COUNT


Description of MAX_COUNT




[options="header",cols="20%,20%,60%"]
|===
|Name|Value|Description
|MAX_COUNT|10000|
Description of MAX_COUNT

|===
